version: "3.8"
services:
  backend:
    restart: always
    image: node:18.4.0-alpine3.14
    build:
      context: ./
      dockerfile: Dockerfile.42-node
    volumes:
      - ./backend/:/app
    depends_on:
      - mongo
    ports:
      - 3000:3000
    networks:
      - mynet
    command: sh -c 'npm install && npm run start:dev'

  frontend:
    restart: always
    image: node:18.4.0-alpine3.14
    volumes:
      - ./frontend/:/app
    depends_on:
        - backend
    ports:
      - '8080:8080'
      - '5173:5173'
      - '80:80'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - mynet
    command: sh -c 'npm install && npm run dev'

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
     - '27017:27017'
    networks:
      - mynet

  mongo-express:
    image: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: test
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    networks:
      - mynet
    depends_on:
      - mongo

networks:
  mynet:
    driver: bridge
